# Generated by Django 3.2.13 on 2023-02-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='город')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='сокращенное наименование')),
                ('slug', models.SlugField(help_text='unique url fragment based on the company short_name', max_length=255, verbose_name='url')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='улица')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='app_companies.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'street',
                'verbose_name_plural': 'streets',
                'db_table': 'streets',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='должность')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_companies.company', verbose_name='предприятие')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='отчество')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='unique url fragment based on the employee full_name', max_length=255, verbose_name='url')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_companies.position', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=10, verbose_name='номер дома')),
                ('phone_number_1', models.CharField(blank=True, max_length=12, verbose_name='телефон 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=12, verbose_name='телефон 1')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app_companies.company', verbose_name='предприятие')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='app_companies.street', verbose_name='улица')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
                'db_table': 'address',
            },
        ),
    ]
