# Generated by Django 3.2.13 on 2023-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
