# Generated by Django 3.2.13 on 2023-02-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0002_company_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='company',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='app_companies.company', verbose_name='предприятие'),
        ),
    ]
