# Generated by Django 4.2.4 on 2023-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0007_rename_full_name_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('last_name',), 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',), 'verbose_name': 'position', 'verbose_name_plural': 'positions'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ('name',), 'verbose_name': 'street', 'verbose_name_plural': 'streets'},
        ),
    ]
