# Generated by Django 4.2.4 on 2023-08-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_companies', '0006_alter_address_phone_number_2'),
        ('app_animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_animals.animalgroup', verbose_name='группа животных'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_companies.company', verbose_name='предприятие'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_animals.animalsex', verbose_name='пол животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_animals.species', verbose_name='вид животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_of_use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_animals.typeofuse', verbose_name='тип использования'),
        ),
        migrations.AlterField(
            model_name='animalgroup',
            name='type_of_feeding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app_animals.typeoffeeding', verbose_name='тип питания'),
        ),
    ]
