# Generated by Django 4.2.4 on 2023-08-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_vet_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='единица учета')),
            ],
            options={
                'verbose_name': 'accounting_unit',
                'verbose_name_plural': 'accounting_units',
                'db_table': 'accounting_units',
            },
        ),
        migrations.CreateModel(
            name='AdministrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='способ применения')),
            ],
            options={
                'verbose_name': 'administration_method',
                'verbose_name_plural': 'administration_methods',
                'db_table': 'administration_methods',
            },
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.TextField(blank=True, verbose_name='дозировка препарата')),
            ],
            options={
                'verbose_name': 'dosage',
                'verbose_name_plural': 'dosages',
                'db_table': 'dosages',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование препарата')),
                ('budget', models.CharField(choices=[('Fed', 'Federal'), ('Reg', 'Regional'), ('Com', 'Commercial')], default='Fed', max_length=3)),
                ('image', models.ImageField(upload_to='drugs/images/')),
                ('instruction', models.FileField(upload_to='drugs/', verbose_name='инструкция к препарату')),
                ('disease', models.ForeignKey(help_text='ссылка на заболевание', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='app_vet_work.disease', verbose_name='заболевание')),
            ],
        ),
        migrations.CreateModel(
            name='DrugManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='производитель препарата')),
            ],
            options={
                'verbose_name': 'drug_manufacturer',
                'verbose_name_plural': 'drug_manufacturers',
                'db_table': 'drug_manufacturers',
            },
        ),
        migrations.CreateModel(
            name='DrugMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('поступление', 'Receipt'), ('расход', 'Expense'), ('уничтожение', 'Destruction')], max_length=20, verbose_name='операция')),
                ('operation_date', models.DateField(blank=True, null=True, verbose_name='дата операции')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(blank=True, verbose_name='место введения препарата')),
            ],
            options={
                'verbose_name': 'place_of_administration',
                'verbose_name_plural': 'place_of_administration',
                'db_table': 'place_of_administration',
            },
        ),
        migrations.CreateModel(
            name='DrugInMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=10, verbose_name='серия')),
                ('control', models.CharField(blank=True, max_length=10, verbose_name='контроль')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='дата выпуска')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='срок годности')),
                ('packing', models.FloatField(help_text='количество единиц учета в единице упаковки', null=True, verbose_name='фасовка')),
                ('packs_amount', models.PositiveSmallIntegerField(null=True, verbose_name='количество упаковок')),
                ('units_amount', models.FloatField(null=True, verbose_name='количество единиц учета')),
                ('available', models.BooleanField(default=True, verbose_name='в наличии')),
                ('drug', models.ForeignKey(blank=True, help_text='ссылка на модель препарат', on_delete=django.db.models.deletion.CASCADE, related_name='drug_in_movement', to='app_drugs.drug', verbose_name='препарат')),
                ('drug_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_in_movement', to='app_drugs.drugmovement', verbose_name='вид перемещения')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_manufacturer',
            field=models.ForeignKey(help_text='ссылка на производителя препарата', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='app_drugs.drugmanufacturer', verbose_name='производитель препарата'),
        ),
    ]
