# Generated by Django 4.2.4 on 2023-08-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_drugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginmovement',
            name='accounting_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_in_movement', to='app_drugs.accountingunit', verbose_name='единицы учета'),
        ),
    ]
