# Generated by Django 4.2.4 on 2023-08-24 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_drugs', '0003_alter_placeofadministration_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginmovement',
            name='accounting_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs_in_movement', to='app_drugs.accountingunit', verbose_name='единицы учета'),
        ),
        migrations.AlterField(
            model_name='druginmovement',
            name='drug',
            field=models.ForeignKey(blank=True, help_text='ссылка на модель препарат', on_delete=django.db.models.deletion.CASCADE, related_name='drugs_in_movement', to='app_drugs.drug', verbose_name='препарат'),
        ),
    ]
