# Generated by Django 4.2.4 on 2023-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drugs', '0004_alter_druginmovement_accounting_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugmovement',
            name='slug',
            field=models.SlugField(blank=True, help_text='unique url fragment based on the drug_movement operation and operation_date', max_length=255, null=True, verbose_name='url'),
        ),
    ]
