# Generated by Django 4.2.4 on 2023-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование болезни')),
            ],
            options={
                'verbose_name': 'disease',
                'verbose_name_plural': 'diseases',
                'db_table': 'diseases',
            },
        ),
    ]
